CREATE TABLE IF NOT EXISTS `Difficulties`(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    Difficulty VARCHAR(20) NOT NULL UNIQUE,
    DaysToRepeat INT NOT NULL,
    Value INTEGER NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS `Nouns` (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    Artikkel VARCHAR(2),
    EntallU VARCHAR(50),
    EntallB VARCHAR(50),
    FlertallU VARCHAR(50),
    FlertallB VARCHAR(50),
    Active BOOLEAN DEFAULT FALSE,
    Regular BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS `Languages` (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    Lang VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS `Translations` (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    LangID INTEGER NOT NULL,
    Translation VARCHAR(50) NOT NULL,
    FOREIGN KEY(LangID) REFERENCES Languages(ID)
);

CREATE TABLE IF NOT EXISTS `Nouns_Translations` (
    NounID INTEGER NOT NULL,
    TranslationID INTEGER NOT NULL,
    PRIMARY KEY(NounID, TranslationID),
    FOREIGN KEY(NounID) REFERENCES Nouns(ID) ON DELETE CASCADE,
    FOREIGN KEY (TranslationID) REFERENCES Translations(ID) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS `Nouns_Synonyms` (
    NounID_1 INTEGER NOT NULL,
    NounID_2 INTEGER NOT NULL,
    PRIMARY KEY(NounID_1, NounID_2),
    FOREIGN KEY(NounID_1) REFERENCES Nouns(ID) ON DELETE CASCADE,
    FOREIGN KEY(NounID_1) REFERENCES Nouns(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `Users` (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    login VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS `Active_User` (
    ID INTEGER PRIMARY KEY NOT NULL UNIQUE,
    FOREIGN KEY(ID) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS `Nouns_Repetitions` (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NounID INTEGER NOT NULL,
    UserID INTEGER NOT NULL,
    DifficultyID INTEGER NOT NULL,
    DateRepeated DATE NOT NULL,
    FOREIGN KEY(NounID) REFERENCES Nouns(ID) ON DELETE CASCADE,
    FOREIGN KEY(UserID) REFERENCES Users(ID) ON DELETE CASCADE
);